### ISSUE TITLE
 Creación de scripts de base de datos

### ISSUE THREAD

**Issue by DenisAGS** [DenisAGS/Nutri-soft#2]
**Description**
Debemos desarrollar y documentar los scripts de la base de datos necesarios para el proyecto. Estos scripts son muy importantes para el funcionamiento de la aplicación y deben estar debidamente diseñados y gestionados.

**Task**
- [x] Diseñar el esquema de la base de datos, incluyendo tablas, relaciones y campos.
- [x] Crear scripts de creación de tablas.
- [x] Generar scripts de población inicial de datos.
- [x] Documentar los scripts de la base de datos.

**Comment by DenisAGS** [comment]
Listo
