### ISSUE TITLE
Realizar un Diagrama arquitectónico

### ISSUE THREAD

**Issue by DenisAGS** [DenisAGS/Nutri-soft#3]
**Description**

Crear un diagrama arquitectónico que represente la estructura y la disposición de componentes clave de nuestro sistema o proyecto

**Task**
- [ ] Identificar y definir los componentes principales del sistema.
- [ ] Diseñar la estructura y las relaciones entre los componentes.
- [ ] Representar la lógica de flujo de datos y control entre los componentes.
